services:
  e-learning-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_DATABASE: ELearning
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  e-learning-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: e-learning-app
    depends_on:
      - e-learning-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=e-learning-db
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  mysql_data: